language: csharp
solution: MonoDevelop.VersionControl.Mercurial/MonoDevelop.VersionControl.Mercurial.sln
mono: latest
install: 
 - nuget restore MonoDevelop.VersionControl.Mercurial
script:
 - cd External
 - ./configure --profile=stable
 - make
 - sudo make install
 - cd ..