language: csharp
solution: MonoDevelop.VersionControl.Mercurial/MonoDevelop.VersionControl.Mercurial.sln
mono: latest
install: 
 - sudo apt-get install monodevelop
 - nuget restore MonoDevelop.VersionControl.Mercurial
script:
 - cd External
 - ./configure --profile=stable
 - make
 - cd ..